### ISSUE TITLE
addServiceコマンドの作成

### ISSUE THREAD

**Issue by tozastation** [tozastation/sgoffold#3]
## TODO
- [ ] : golang-standards/project-layout配下に，サービス用のディレクトリを作る
- [ ] : buildに開発と本番用のDockerfileを作る
- [ ] : .realize.yamlに追加したサービスを追記する
- [ ] : deployments/docker-compose.dev.yaml を作成
- [ ] : deployments/docker-compose.prod.yaml を作成
- [ ] : clean architecture でディレクトリを初期化

---
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
